version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: home-library-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    networks:
      - backend

  app:
    build: .
    container_name: home-library-app
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  db-data:
  db-logs:

networks:
  backend:
    driver: bridge
